# Generated by Django 4.0.1 on 2022-01-24 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacto', '0002_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=200)),
                ('Apellido', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Telefono', models.CharField(max_length=15)),
                ('Asunto', models.TextField()),
                ('Mesaje', models.TextField()),
            ],
        ),
    ]
