# Generated by Django 4.0.1 on 2022-01-24 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0004_alter_contactos_asunto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=200)),
                ('Apellido', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Telefono', models.CharField(max_length=15)),
                ('Asunto', models.CharField(max_length=200)),
                ('Mesaje', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Contactos',
        ),
    ]
