# Generated by Django 4.0.1 on 2022-02-21 16:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0006_rename_mesaje_contacto_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 2, 21, 16, 36, 51, 718143, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
