# Generated by Django 4.0.1 on 2022-01-23 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0003_alter_cliente_anio_proyecto_alter_cliente_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='anio_proyecto',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nombre_proyecto',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='tipo_proyecto',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre_cliente',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_proyecto', models.CharField(max_length=50)),
                ('nombre_proyecto', models.CharField(max_length=500)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='proyectos')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('clientes', models.ManyToManyField(to='clientes.Cliente')),
            ],
            options={
                'verbose_name': 'proyecto',
                'verbose_name_plural': 'proyectos',
            },
        ),
    ]
