# Generated by Django 4.0.1 on 2022-01-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_alter_proyecto_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='nombre_proyecto',
            field=models.TextField(max_length=500),
        ),
    ]
