# Generated by Django 4.0.1 on 2022-02-19 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_alter_proyecto_nombre_proyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('productos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.proyecto')),
            ],
        ),
    ]
