# Generated by Django 4.0.1 on 2022-02-19 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_proyectocliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='clientes',
            field=models.ManyToManyField(through='clientes.ProyectoCliente', to='clientes.Cliente'),
        ),
    ]
