# Generated by Django 4.0.1 on 2022-02-19 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_alter_proyecto_clientes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyectocliente',
            options={'verbose_name': 'proyectocliente', 'verbose_name_plural': 'proyectosclientes'},
        ),
    ]
