# Generated by Django 4.0.1 on 2022-02-20 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_alter_proyectocliente_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyectocliente',
            options={},
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='clientes',
            field=models.ManyToManyField(to='clientes.Cliente'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nombre_proyecto',
            field=models.CharField(max_length=500),
        ),
    ]
