# Generated by Django 4.0.1 on 2022-02-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0012_proyecto_imagen_delete_proyectocliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='imagen',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='proyectos'),
        ),
    ]
